name: Auto Green Marker

on:
  schedule:
    # - cron: '53 0 * * *'  # 每天运行一次，时间可以根据需要调整
    - cron: '30 0/6 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # 禁用默认的GITHUB_TOKEN

      - name: Pull remote changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git pull origin main --no-rebase  # 使用合并策略拉取更改
      - name: Configure Git
        run: |
          git config --global user.email "dev.zhouxun@outlook.com"
          git config --global user.name "zx123456"
      - name: Make a change
        run: echo "$(date)" >> commit.txt  # 使用追加操作符避免冲突

      - name: Commit changes
        run: |
          git add commit.txt
          git commit -m "Automated commit" || echo "No changes to commit"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main